name: Validate, build, and test on every push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.18.1
          cache: 'yarn'
      - name: Install dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - name: Hardhat compile
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build
  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run prettier
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: format
      - name: Lint JS files
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: lint
      - name: Lint Solidity files
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: lint:sol
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run Hardhat tests
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: test
      - name: Check Solidity coverage
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: coverage
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test contract deployment
        continue-on-error: false
        run: npx hardhat node --network hardhat
