name: Validate, build, and test on every push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0
          cache: 'yarn'
      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Hardhat compile
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: Run prettier
        uses: borales/actions-yarn@v4
        with:
          cmd: format
      - name: Lint JS files
        uses: borales/actions-yarn@v4
        with:
          cmd: lint
      - name: Lint Solidity files
        uses: borales/actions-yarn@v4
        with:
          cmd: lint:sol
      - name: Check TypeScript
        uses: borales/actions-yarn@v4
        with:
          cmd: type-check
      - name: Run Hardhat tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test
      - name: Check Solidity coverage
        uses: borales/actions-yarn@v4
        with:
          cmd: coverage
      - name: Test contract deployment
        continue-on-error: false
        run: npx hardhat run --network hardhat src/scripts/deploy_test.ts
